### ISSUE TITLE
Hangs indefinitely

### ISSUE THREAD

**Issue by Tak1za** [allenkim67/allen-torrent#6]
As soon as I run,
node index.js torr.torrent
(torr.torrent is the name of the torrent and its in the root of the project)
everything just hangs. 
I don't even get an output for the connected peers.

Also, the torrent I'm using has a lot of peers and it works fine when I use BitTorrent.

**Comment by karanmottan** [comment]
i'm facing the same problem , could you tell me how you solved it?
